name: 'Prepare environment'
description: 'Prepare environment'

runs:
  using: "composite"
  steps:
    - name: Show ubuntu version
      run: lsb_release -a
      shell: bash
    - run: sudo apt-get update
      shell: bash
    - run: sudo apt search libgdal
      shell: bash
    - name: Setup libraries
      run: |
        sudo apt-get install -y \
          pkg-config \
          libcairo2-dev \
          libmariadb-dev \
          pipx \
          gcc \
          && sudo apt-get install -y libgdal30 || sudo apt-get install -y libgdal26
      shell: bash
    - name: Install Poetry
      run: pipx install poetry
      shell: bash
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install --only main,dev --no-interaction --no-ansi
      shell: bash
